'use client';

import { FormEvent, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { ManagerWorkspace, SalesClient, SalesDeal, SalesTask } from '@/lib/manager-crm';
import type { PaymentOrder, SalesAnalytics } from '@/lib/payment-orders';

const money = (kopecks: number) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(kopecks / 100);
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : 'Не указан';
const stageNames: Record<string, string> = { new: 'Новая', qualification: 'Квалификация', proposal: 'Предложение', negotiation: 'Согласование', awaiting_payment: 'Ожидает оплаты', won: 'Успешно', lost: 'Потеряна' };
const stages = Object.entries(stageNames);
const sourceNames: Record<string, string> = { manager: 'Менеджер', website: 'Сайт', phone: 'Звонок', messenger: 'Мессенджер', recommendation: 'Рекомендация', other: 'Другое' };
const priorityNames: Record<string, string> = { low: 'Низкий', normal: 'Обычный', high: 'Высокий' };

async function request(body: Record<string, unknown>, method = 'POST') {
  const response = await fetch('/api/manager/crm', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.error || 'Не удалось сохранить изменения');
}

function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-[120] grid place-items-center overflow-y-auto bg-black/45 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="my-5 w-full max-w-xl rounded-3xl bg-[#fbfaf8] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-terracotta">{subtitle}</p><h2 className="mt-2 font-serif text-3xl">{title}</h2></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full border border-black/10 text-xl text-black/45">×</button></div>{children}</div></div>;
}

function CrmForm({ kind, workspace, onClose }: { kind: 'client' | 'deal' | 'task' | 'activity'; workspace: ManagerWorkspace; onClose: () => void }) {
  const router = useRouter();
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSaving(true); setError('');
    const data = Object.fromEntries(new FormData(event.currentTarget));
    try { await request({ entity: kind, ...data }); router.refresh(); onClose(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Не удалось сохранить'); }
    finally { setSaving(false); }
  };
  const input = 'w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-xs outline-none focus:border-terracotta';
  const titles = { client: ['Новый клиент', 'Клиентская база'], deal: ['Новая сделка', 'Воронка продаж'], task: ['Новая задача', 'Планирование'], activity: ['Новая заметка', 'История контактов'] } as const;
  return <Modal title={titles[kind][0]} subtitle={titles[kind][1]} onClose={onClose}><form onSubmit={submit} className="mt-6 grid gap-3">
    {kind === 'client' && <><input required name="fullName" placeholder="Имя клиента" className={input}/><div className="grid gap-3 sm:grid-cols-2"><input name="phone" placeholder="Телефон" className={input}/><input name="email" type="email" placeholder="Email" className={input}/></div><div className="grid gap-3 sm:grid-cols-2"><input name="city" placeholder="Город" className={input}/><select name="source" className={input}><option value="manager">Добавлен менеджером</option><option value="website">Сайт</option><option value="phone">Входящий звонок</option><option value="messenger">Мессенджер</option><option value="recommendation">Рекомендация</option><option value="other">Другое</option></select></div><textarea name="notes" placeholder="Что важно знать о клиенте" className={`${input} min-h-24`}/><label className="text-[10px] text-black/45">Следующий контакт<input name="nextContactAt" type="datetime-local" className={`mt-1.5 ${input}`}/></label></>}
    {kind === 'deal' && <><select required name="clientId" className={input}><option value="">Выберите клиента</option>{workspace.clients.map((client) => <option key={client.id} value={client.id}>{client.fullName} · {client.phone || client.email}</option>)}</select><input required name="title" placeholder="Название сделки" className={input}/><div className="grid gap-3 sm:grid-cols-2"><input name="amount" type="number" min="0" step="1" placeholder="Плановая сумма, ₽" className={input}/><input name="probability" type="number" min="0" max="100" defaultValue="20" placeholder="Вероятность, %" className={input}/></div><input name="productInterest" placeholder="Интересующие товары" className={input}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-black/45">План закрытия<input name="expectedCloseDate" type="date" className={`mt-1.5 ${input}`}/></label><label className="text-[10px] text-black/45">Следующий контакт<input name="nextContactAt" type="datetime-local" className={`mt-1.5 ${input}`}/></label></div><textarea name="notes" placeholder="Комментарий к сделке" className={`${input} min-h-24`}/></>}
    {kind === 'task' && <><input required name="title" placeholder="Что нужно сделать" className={input}/><textarea name="description" placeholder="Описание или результат, который нужен" className={`${input} min-h-20`}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-black/45">Срок<input required name="dueAt" type="datetime-local" className={`mt-1.5 ${input}`}/></label><label className="text-[10px] text-black/45">Приоритет<select name="priority" defaultValue="normal" className={`mt-1.5 ${input}`}><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option></select></label></div><select name="clientId" className={input}><option value="">Без привязки к клиенту</option>{workspace.clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select><select name="dealId" className={input}><option value="">Без привязки к сделке</option>{workspace.deals.filter((deal) => !['won','lost'].includes(deal.stage)).map((deal) => <option key={deal.id} value={deal.id}>{deal.title} · {deal.clientName}</option>)}</select></>}
    {kind === 'activity' && <><select name="clientId" className={input}><option value="">Выберите клиента</option>{workspace.clients.map((client) => <option key={client.id} value={client.id}>{client.fullName}</option>)}</select><select name="dealId" className={input}><option value="">Или выберите сделку</option>{workspace.deals.map((deal) => <option key={deal.id} value={deal.id}>{deal.title} · {deal.clientName}</option>)}</select><textarea required name="description" placeholder="Итог звонка, договорённость или важная заметка" className={`${input} min-h-28`}/></>}
    {error && <p className="rounded-xl bg-red-50 px-4 py-3 text-xs text-red-700">{error}</p>}<button disabled={saving} className="mt-2 rounded-full bg-terracotta py-3.5 text-xs font-semibold text-white disabled:opacity-50">{saving ? 'Сохраняем…' : 'Сохранить'}</button>
  </form></Modal>;
}

function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-dashed border-black/15 bg-white/45 px-6 py-12 text-center text-sm text-black/40">{children}</div>; }

export function ManagerCrm({ mode, workspace, query }: { mode: 'Клиенты' | 'Сделки' | 'Задачи'; workspace: ManagerWorkspace; query: string }) {
  const router = useRouter();
  const [modal, setModal] = useState<'client' | 'deal' | 'task' | 'activity' | null>(null);
  const [busy, setBusy] = useState('');
  const q = query.trim().toLowerCase();
  const clients = workspace.clients.filter((item) => `${item.fullName} ${item.phone || ''} ${item.email || ''} ${item.city || ''}`.toLowerCase().includes(q));
  const deals = workspace.deals.filter((item) => `${item.title} ${item.clientName} ${item.productInterest || ''}`.toLowerCase().includes(q));
  const tasks = workspace.tasks.filter((item) => `${item.title} ${item.clientName || ''} ${item.dealTitle || ''}`.toLowerCase().includes(q));
  const update = async (body: Record<string, unknown>) => { setBusy(`${body.entity}-${body.id}`); try { await request(body, 'PATCH'); router.refresh(); } finally { setBusy(''); } };
  const heading = mode === 'Клиенты' ? ['Клиенты', 'Контакты, история общения и потенциал клиента'] : mode === 'Сделки' ? ['Сделки', 'Рабочая воронка от первого интереса до оплаты'] : ['Задачи', 'Звонки, встречи и контроль обещаний'];
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-terracotta">CRM менеджера</p><h1 className="mt-2 font-serif text-4xl">{heading[0]}</h1><p className="mt-2 text-xs text-black/45">{heading[1]}</p></div><div className="flex gap-2">{mode === 'Клиенты' && <button onClick={() => setModal('activity')} className="rounded-full border border-black/15 bg-white px-4 py-3 text-xs font-semibold">+ Заметка</button>}<button onClick={() => setModal(mode === 'Клиенты' ? 'client' : mode === 'Сделки' ? 'deal' : 'task')} className="rounded-full bg-terracotta px-5 py-3 text-xs font-semibold text-white">+ {mode === 'Клиенты' ? 'Клиент' : mode === 'Сделки' ? 'Сделка' : 'Задача'}</button></div></div>
    {mode === 'Клиенты' && <div className="mt-7 grid gap-3 lg:grid-cols-2">{clients.map((client) => <article key={client.id} className="rounded-2xl border border-black/[.07] bg-white p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#efe7dc] font-serif text-terracotta">{client.fullName.split(/\s+/).map((part) => part[0]).join('').slice(0,2).toUpperCase()}</span><div className="min-w-0"><h2 className="truncate text-sm font-semibold">{client.fullName}</h2><p className="mt-1 text-[10px] text-black/40">{client.phone || 'Телефон не указан'} · {client.email || 'email не указан'}</p><p className="mt-1 text-[10px] text-black/40">{client.city || 'Город не указан'} · {sourceNames[client.source] || client.source}</p></div></div><select disabled={busy === `client-${client.id}`} value={client.status} onChange={(event) => update({ entity:'client', id:client.id, status:event.target.value })} className="rounded-full border border-black/10 bg-white px-2 py-1 text-[9px]"><option value="active">Активный</option><option value="vip">VIP</option><option value="inactive">Неактивный</option></select></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-black/[.025] p-3 text-center"><div><p className="text-[9px] text-black/35">Сделок</p><strong className="mt-1 block text-xs">{client.dealsCount}</strong></div><div><p className="text-[9px] text-black/35">Потенциал</p><strong className="mt-1 block text-xs">{money(client.dealsAmountKopecks)}</strong></div><div><p className="text-[9px] text-black/35">Контакт</p><strong className="mt-1 block text-[10px]">{dateTime(client.nextContactAt)}</strong></div></div>{client.notes && <p className="mt-3 line-clamp-2 text-[10px] leading-4 text-black/50">{client.notes}</p>}<div className="mt-4 flex gap-2">{client.phone && <a href={`tel:${client.phone}`} className="rounded-full bg-[#242421] px-4 py-2 text-[10px] font-semibold text-white">Позвонить</a>}{client.email && <a href={`mailto:${client.email}`} className="rounded-full border border-black/10 px-4 py-2 text-[10px] font-semibold">Написать</a>}</div></article>)}{clients.length === 0 && <div className="lg:col-span-2"><Empty>{workspace.clients.length ? 'По запросу ничего не найдено' : 'Клиентов пока нет. Добавьте первый контакт, чтобы начать вести историю.'}</Empty></div>}</div>}
    {mode === 'Сделки' && <div className="mt-7 overflow-x-auto pb-2"><div className="grid min-w-[1160px] grid-cols-7 gap-3">{stages.map(([stage, label]) => { const items = deals.filter((deal) => deal.stage === stage); return <section key={stage} className="rounded-2xl bg-black/[.035] p-3"><div className="flex items-center justify-between"><h2 className="text-[10px] font-semibold uppercase tracking-[.1em]">{label}</h2><span className="rounded-full bg-white px-2 py-1 text-[9px]">{items.length}</span></div><p className="mt-2 text-[10px] text-black/35">{money(items.reduce((sum,item)=>sum+item.amountKopecks,0))}</p><div className="mt-3 space-y-2">{items.map((deal) => <article key={deal.id} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-[11px] font-semibold leading-4">{deal.title}</p><p className="mt-1 text-[9px] text-black/40">{deal.clientName}</p><p className="mt-3 text-xs font-semibold">{money(deal.amountKopecks)}</p><div className="mt-2 h-1 rounded-full bg-black/[.06]"><div className="h-full rounded-full bg-terracotta" style={{width:`${deal.probability}%`}}/></div>{deal.nextContactAt && <p className="mt-2 text-[9px] text-black/40">Контакт: {dateTime(deal.nextContactAt)}</p>}<select disabled={busy === `deal-${deal.id}`} value={deal.stage} onChange={(event) => update({ entity:'deal', id:deal.id, stage:event.target.value })} className="mt-3 w-full rounded-lg border border-black/10 bg-white px-2 py-1.5 text-[9px]">{stages.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></article>)}{items.length === 0 && <p className="rounded-xl border border-dashed border-black/10 py-7 text-center text-[9px] text-black/25">Пусто</p>}</div></section>; })}</div>{workspace.deals.length === 0 && <div className="mt-4"><Empty>Создайте первую сделку и двигайте её по этапам воронки.</Empty></div>}</div>}
    {mode === 'Задачи' && <div className="mt-7 space-y-3">{tasks.map((task) => { const overdue = task.status === 'open' && new Date(task.dueAt).getTime() < Date.now(); return <article key={task.id} className={`grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[auto_1fr_auto] sm:items-center ${overdue ? 'border-red-200' : 'border-black/[.07]'} ${task.status === 'done' ? 'opacity-50' : ''}`}><button disabled={busy === `task-${task.id}`} onClick={() => update({entity:'task',id:task.id,status:task.status === 'done' ? 'open' : 'done'})} className={`grid h-7 w-7 place-items-center rounded-full border text-xs ${task.status === 'done' ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-black/20'}`}>{task.status === 'done' ? '✓' : ''}</button><div><div className="flex flex-wrap items-center gap-2"><h2 className={`text-sm font-semibold ${task.status === 'done' ? 'line-through' : ''}`}>{task.title}</h2><span className={`rounded-full px-2 py-1 text-[9px] ${task.priority === 'high' ? 'bg-red-50 text-red-700' : task.priority === 'low' ? 'bg-black/[.04] text-black/45' : 'bg-amber-50 text-amber-700'}`}>{priorityNames[task.priority]}</span></div><p className={`mt-1 text-[10px] ${overdue ? 'font-semibold text-red-600' : 'text-black/40'}`}>{overdue ? 'Просрочено · ' : ''}{dateTime(task.dueAt)}{task.clientName ? ` · ${task.clientName}` : ''}{task.dealTitle ? ` · ${task.dealTitle}` : ''}</p>{task.description && <p className="mt-2 text-[10px] text-black/50">{task.description}</p>}</div><button onClick={() => update({entity:'task',id:task.id,status:'cancelled'})} className="text-[10px] text-black/30 hover:text-red-600">Отменить</button></article>; })}{tasks.length === 0 && <Empty>{workspace.tasks.length ? 'По запросу ничего не найдено' : 'Задач пока нет. Запланируйте звонок, встречу или контроль оплаты.'}</Empty>}</div>}
    {modal && <CrmForm kind={modal} workspace={workspace} onClose={() => setModal(null)}/>}</div>;
}

export function ManagerOverview({ workspace, orders, analytics, onOpen }: { workspace: ManagerWorkspace; orders: PaymentOrder[]; analytics: SalesAnalytics; onOpen: (section: string) => void }) {
  const openTasks = workspace.tasks.filter((task) => task.status === 'open');
  const overdue = openTasks.filter((task) => new Date(task.dueAt).getTime() < Date.now());
  const activeDeals = workspace.deals.filter((deal) => !['won','lost'].includes(deal.stage));
  const pipeline = activeDeals.reduce((sum, deal) => sum + deal.amountKopecks, 0);
  const attentionPayments = orders.filter((order) => ['created','payment_initialized','payment_init_failed','payment_failed'].includes(order.status));
  const cards = [
    { label:'Выручка', value:money(analytics.revenueKopecks), note:`${analytics.paidOrders} оплаченных заказов`, section:'Аналитика' },
    { label:'Активные сделки', value:String(activeDeals.length), note:`Потенциал ${money(pipeline)}`, section:'Сделки' },
    { label:'Задачи', value:String(openTasks.length), note:overdue.length ? `${overdue.length} просрочено` : 'Просроченных нет', section:'Задачи' },
    { label:'Платежи в работе', value:String(attentionPayments.length), note:`Всего заказов: ${orders.length}`, section:'Платежи' },
  ];
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-terracotta">Рабочий день</p><h1 className="mt-2 font-serif text-4xl">Центр продаж</h1><p className="mt-2 text-xs text-black/45">Только реальные данные: клиенты, сделки, задачи и оплаты.</p></div><button onClick={() => onOpen('Сделки')} className="rounded-full bg-terracotta px-5 py-3 text-xs font-semibold text-white">+ Новая сделка</button></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card)=><button key={card.label} onClick={()=>onOpen(card.section)} className="rounded-2xl border border-black/[.06] bg-white p-5 text-left"><p className="text-[10px] text-black/40">{card.label}</p><p className="mt-3 text-2xl font-semibold">{card.value}</p><p className={`mt-2 text-[10px] ${card.note.includes('просрочено') ? 'text-red-600' : 'text-black/40'}`}>{card.note}</p></button>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="rounded-2xl border border-black/[.06] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-serif text-2xl">Ближайшие задачи</h2><p className="mt-1 text-[10px] text-black/40">Что требует внимания в первую очередь</p></div><button onClick={()=>onOpen('Задачи')} className="text-[10px] font-semibold text-terracotta">Все задачи →</button></div><div className="mt-5 divide-y divide-black/[.06]">{openTasks.slice(0,6).map((task)=><button key={task.id} onClick={()=>onOpen('Задачи')} className="flex w-full items-center gap-3 py-3 text-left"><span className={`h-2 w-2 rounded-full ${task.priority === 'high' ? 'bg-red-500' : 'bg-amber-400'}`}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{task.title}</span><span className="mt-1 block text-[9px] text-black/40">{task.clientName || 'Без клиента'} · {dateTime(task.dueAt)}</span></span></button>)}{openTasks.length === 0 && <p className="py-9 text-center text-xs text-black/35">На сегодня задач нет</p>}</div></section><section className="rounded-2xl bg-[#292925] p-5 text-white sm:p-6"><h2 className="font-serif text-2xl">Последние действия</h2><p className="mt-1 text-[10px] text-white/35">История работы в CRM</p><div className="mt-5 space-y-4">{workspace.activities.slice(0,6).map((activity)=><div key={activity.id} className="border-l border-white/15 pl-3"><p className="text-[10px] leading-4 text-white/80">{activity.description}</p><p className="mt-1 text-[8px] text-white/30">{activity.clientName || activity.dealTitle || 'CRM'} · {dateTime(activity.createdAt)}</p></div>)}{workspace.activities.length === 0 && <p className="py-8 text-center text-[10px] text-white/30">История появится после первого действия</p>}</div></section></div></div>;
}
