'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

const slides = [
  { kicker: 'Домашнее тепло', title: 'Место, где вас всегда ждут', text: 'Создайте уютный уголок для тихих вечеров рядом с теми, кто дорог.', image: '/images/hero-labrador-v1.png' },
  { kicker: 'У камина', title: 'Там, где дому становится теплее', text: 'Выберите камин, вокруг которого захочется собираться всей семьёй.', image: '/images/hero-family-v1.png' },
  { kicker: 'Тепло без спешки', title: 'Вечера, которые хочется продлить', text: 'Подберём модель, рассчитаем монтаж и доставим в любой регион.', image: '/images/hero-mother-v1.png' },
];

export function PromoCarousel() { const [active, setActive] = useState(0); const slide = slides[active]; useEffect(() => { const timer = window.setInterval(() => setActive((current) => (current + 1) % slides.length), 6500); return () => window.clearInterval(timer); }, []); return <section className="relative min-h-[600px] overflow-hidden bg-ink sm:min-h-[640px]"><div className="absolute inset-0 bg-cover bg-center opacity-90 transition-all duration-700" style={{ backgroundImage: `url(${slide.image})` }} /><div className="absolute inset-0 bg-gradient-to-r from-ink/75 via-ink/45 to-transparent" /><div className="container-page relative flex min-h-[600px] items-end pb-20 pt-24 sm:min-h-[640px] sm:pb-24"><div className="max-w-2xl text-white"><p className="mb-5 text-[10px] font-semibold uppercase tracking-[.24em] text-gold-light">{slide.kicker}</p><h1 className="max-w-xl font-serif text-5xl leading-[.98] tracking-[-.04em] sm:text-6xl lg:text-7xl">{slide.title}</h1><p className="mt-7 max-w-lg text-base leading-7 text-white/85">{slide.text}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/catalog" className="inline-flex rounded-full bg-white px-6 py-3 text-sm font-medium text-ink transition hover:bg-terracotta hover:text-white">Выбрать камин</Link><a href="tel:+74951234567" className="inline-flex rounded-full border border-white/55 px-6 py-3 text-sm font-medium text-white transition hover:border-white hover:bg-white/10">Получить консультацию</a></div></div></div><div className="absolute bottom-8 right-6 flex gap-2 sm:right-12">{slides.map((_, index) => <button key={index} aria-label={`Перейти к фотографии ${index + 1}`} onClick={() => setActive(index)} className={`h-2 rounded-full transition ${active === index ? 'w-9 bg-white' : 'w-2 bg-white/45 hover:bg-white/70'}`} />)}</div></section>; }
