import Link from 'next/link';
import { notFound } from 'next/navigation';
import { formatPrice } from '@/lib/products';
import { getCompatibleProducts, getProduct } from '@/lib/catalog-repository';
import { ProductGallery } from '@/components/product-gallery';
import { ProductSpecifications } from '@/components/product-specifications';
import { CompatibleProducts } from '@/components/compatible-products';
import { ProductActions } from '@/components/product-actions';

export const dynamic = 'force-dynamic';

export default async function ProductPage({ params }: { params: { id: string } }) { const product = await getProduct(params.id); if (!product) notFound(); const compatibility = await getCompatibleProducts(product.id); const availability = product.availability?.moscow || product.availability?.saintPetersburg; return <section className="container-page py-10 sm:py-16"><p className="text-sm text-ink/50"><Link href="/catalog">Каталог</Link> / {product.name}</p><div className="mt-6 grid gap-9 lg:grid-cols-2"><ProductGallery images={product.images.length ? product.images : [product.image]} name={product.name} /><div className="lg:pt-4"><p className="text-xs uppercase tracking-[.18em] text-terracotta">{product.type}</p><div className="mt-3 flex items-start justify-between gap-4"><h1 className="font-serif text-4xl sm:text-5xl">{product.name}</h1><ProductActions productId={product.id} placement="detail" /></div>{product.article && <p className="mt-3 text-sm text-ink/50">Артикул: <span className="font-medium text-ink">{product.article}</span></p>}<p className="mt-5 text-lg leading-8 text-ink/70">{product.description}</p><div className="mt-7 border-y border-ink/10 py-5"><p className="font-serif text-3xl">{formatPrice(product.price)}</p>{product.oldPrice && <p className="mt-1 text-ink/40 line-through">{formatPrice(product.oldPrice)}</p>}<p className="mt-2 text-sm text-emerald-700">{availability ? `Наличие: ${availability}` : `В наличии: ${product.stock} шт.`}</p></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-ink/50">Габариты</dt><dd className="mt-1 font-medium">{product.dimensions}</dd></div><div><dt className="text-ink/50">Рассрочка</dt><dd className="mt-1 font-medium">Яндекс Сплит</dd></div></dl><button className="mt-8 w-full rounded-full bg-terracotta px-6 py-4 font-medium text-white transition hover:bg-terracotta-dark">Добавить в корзину</button><p className="mt-3 text-center text-xs text-ink/50">Можно оплатить частями через Яндекс Сплит</p></div></div>{compatibility && <CompatibleProducts title={compatibility.title} products={compatibility.products} />}<ProductSpecifications specifications={product.specifications} /></section>; }
